services:
  db:
    image: postgres:15
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD : ${DB_PASS}
      POSTGRES_DB       : ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data